"""Context-pack v1 renderer — writes the project rules that inject memory into chats.

Read this first if you are new to the codebase:
  - ``render_context_pack(workspace_root)`` is the entry point. It picks
    the right work-state adapter (coding vs management), merges the
    workspace and global memory bank via ``scope.merge_context_sources``,
    and writes both ``work-state.md`` and ``context-pack.md`` inside the
    store.
  - ``render_rule_file`` also writes one project rule per tool listed under
    ``tools`` in ``config.json``: ``.cursor/rules/_memory-context.mdc`` for
    Cursor and ``.claude/rules/_memory-context.md`` for Claude Code. OpenCode
    has no project rule; its plugin injects the stored pack.
  - The Cursor ``RULE_HEADER`` carries ``alwaysApply: true`` so Cursor injects
    the pack into every new chat. Claude Code loads every rule without a
    ``paths`` field at launch, so its header is plain Markdown.
  - Rule writes take the store lock with a 0.1-second timeout so a hook never
    hangs on it; ``LockTimeout`` reaches the caller, which fails open.
  - ``session_start_top_up`` returns the small sessionStart hint, or after a
    compaction the conversation's handoff note (see ``recall.handoff``).
  - This is the v1 renderer. The newer ``context_pack_v2`` module computes
    topic-aware, score-weighted output; both ship in parallel during the
    v2 rollout.

Public interface (imported elsewhere): ``render_context_pack``,
    ``render_rule_file``, ``session_start_top_up``, ``RULE_HEADER``,
    ``CLAUDE_RULE_HEADER``.
Depends on: adapters.base, config, paths, recall.handoff, safety, scope.
Used by: events.worker (renders on every heavy pass); ``bin/memory``.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

from memory_system.adapters.base import pick_adapter
from memory_system.system.config import load_config
from memory_system.paths import (
    ensure_layout,
    ensure_local_gitignore,
    generated_rule_paths,
    lock_path,
    workspace_store,
)
from memory_system.recall.handoff import consume_handoff
from memory_system.safety import LockTimeout, atomic_write, file_lock
from memory_system.scope import merge_context_sources

RULE_LOCK_TIMEOUT = 0.1

RULE_HEADER = """---
description: Auto-generated memory context pack (silly-memory). Do not edit manually.
alwaysApply: true
---

# Memory Context

This file is generated by silly-memory. Edit durable facts via memory skills or let observe/reflect update the store.

"""

CLAUDE_RULE_HEADER = """# Memory Context

This file is generated by silly-memory. Do not edit it manually; edit durable facts via memory skills or let observe/reflect update the store.

"""

_RULE_HEADERS = {"cursor": RULE_HEADER, "claude-code": CLAUDE_RULE_HEADER}


def _configured_tools() -> list[str]:
    tools = load_config().get("tools", ["cursor"])
    if not isinstance(tools, list):
        return ["cursor"]
    return [tool for tool in tools if isinstance(tool, str)]


def render_context_pack(workspace_root: Path) -> str:
    store = workspace_store(workspace_root)
    ensure_layout(store)
    adapter = pick_adapter(workspace_root)
    work_state = adapter.snapshot(workspace_root)
    atomic_write(store / "work-state.md", work_state)
    pack = merge_context_sources(workspace_root)
    atomic_write(store / "context-pack.md", pack)
    return pack


def render_rule_file(workspace_root: Path) -> Path:
    """Refresh the stored pack and every configured tool's project rule.

    Returns the Cursor rule when Cursor is configured, else the first rule
    written, else the stored ``context-pack.md``.
    """
    pack = render_context_pack(workspace_root)
    tools = _configured_tools()
    targets = generated_rule_paths(workspace_root, tools)
    ensure_local_gitignore(workspace_root, tools)
    store = workspace_store(workspace_root)
    with file_lock(lock_path(store), timeout=RULE_LOCK_TIMEOUT):
        for tool, rule_path in targets.items():
            atomic_write(rule_path, _RULE_HEADERS[tool] + pack)
    if "cursor" in targets:
        return targets["cursor"]
    return next(iter(targets.values()), store / "context-pack.md")


def session_start_top_up(
    workspace_root: Path,
    session_source: str = "startup",
    source: str | None = None,
    conversation_id: str | None = None,
    handoff_token: str | None = None,
) -> str | None:
    """sessionStart additional context: after a compaction, that conversation's handoff note.

    Anything else, including a compaction with no matching note, gets the small
    refresh hint. OpenCode must pass the ``handoff_token`` of its current
    compaction attempt; Claude Code relies on its own compact SessionStart.
    """
    if session_source == "compact" and source and conversation_id:
        try:
            restored = consume_handoff(
                workspace_store(workspace_root),
                source,
                conversation_id,
                token=handoff_token,
                require_token=source == "opencode",
            )
        except LockTimeout:
            restored = None
        if restored:
            return restored
    today = date.today().isoformat()
    return f"silly-memory pack refreshed {today}. Use `memory recall` for older facts not in the injected pack."
